#!/bin/bash

if [[ $# -ne 5 ]]; then
	echo "Usage: $0 prmtop inpcrd step nrep basename"
	echo "prmtop:   <file> input topology"
	echo "inpcrd:   <file> input coordinates"
	echo "step:     <file[,file]> configuration file."
	echo "          If two files are given, the first file will be used just for the first step."
	echo "nrep:     <num>  number of times step is repeated"
	echo "basename: <name> output files basename"
	exit 1
fi

[[ -n $TEST ]] && echo="echo"

PRMTOP=$1
INPCRD=$2
IFS=$'\n, ' read -r -a steps <<<"$3"
NREP=$4
NAME=$5

inpcrd=$INPCRD
for ((i = 1; i <= 10#${NREP}; i++)); do
	step=$(printf "%0${#NREP}d" "$i")
	if [[ ! -f "${NAME}_step_${step}.ok" ]]; then
		echo "Step $step"

		if [[ $i -gt 1 && ${#steps[@]} -gt 1 ]]; then
			mdin=${steps[1]}
		else
			mdin=${steps[0]}
		fi

		if grep -q 'imin\s*=\s*1' "$mdin"; then
			prog="$AMBERHOME/bin/pmemd.cuda_DPFP"
			if [[ $mdin =~ _CPU ]]; then
				prog="$AMBERHOME/bin/pmemd"
			fi
		else
			prog="$AMBERHOME/bin/pmemd.cuda"
		fi

		"$echo" "$prog" -O -i "$mdin" -o "${NAME}_${step}.mdout" -p "$PRMTOP" -c "$inpcrd" -r "${NAME}_${step}.rst7" -ref "$inpcrd" -inf "${NAME}_${step}.mdinfo" -x "${NAME}_${step}.nc" || exit 1
		touch "${NAME}_step_${step}.ok"
		echo "done: $(date)"
		echo
	fi
	inpcrd="${NAME}_${step}.rst7"
done
