#!/bin/bash

if [[ $# -ne 5 ]]; then
    echo "Usage: $0 prmtop inpcrd basename protdir"
    echo "prmtop:   <file> input topology"
    echo "inpcrd:   <file> input coordinates"
    echo "protdir:  <dir>  protocol directory"
    echo "protglob: <string> glob pattern matching protocol files"
    echo "basename: <name> output files basename"
    echo
    echo "Note: Protocol files (mdin) are searched for in 'protdir' with 'ptrotglob' query and sorted"
    exit 1
fi

PRMTOP=$1
INPCRD=$2
PROTDIR=$3
PROTGLOB=$4
NAME=$5

mapfile -t infiles < <(find "$PROTDIR" -maxdepth 1 -name "$PROTGLOB" | sort)
echo "processing step files:"
printf "%s" "${infiles[@]}"
echo

inpcrd=$INPCRD
for inp in "${infiles[@]}"; do
    step=${inp%.*}
    if [[ ! -f "${NAME}_step_${step}.ok" ]]; then
        echo "Stage $step: $inp - $(head -n 1 "$inp")"

        grep -q 'imin\s*=\s*1' "$inp" && prog="$AMBERHOME/bin/pmemd.cuda_DPFP" || prog="$AMBERHOME/bin/pmemd.cuda"
        "$prog" -O -i "$inp" -o "${NAME}_${step}.mdout" -p "$PRMTOP" -c "$inpcrd" -r "${NAME}_${step}.rst7" -ref "$inpcrd" -inf "${NAME}_${step}.mdinfo" -x "${NAME}_${step}.nc" || exit 1
        touch "${NAME}_step_${step}.ok"
        echo "done: $(date)"
        echo
    fi
    inpcrd="${NAME}_${step}.rst7"
done
